name: Test & Lint

on:
  push:
    branches:
      - '*'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: npm install, build, and test
        run: |
          npm install
          npm run test
          npm run typecheck
          npm run lint
        env:
          CI: true
