# TODO bump version in manifest.json automatically
# on:
#   workflow_dispatch:

# name: Publish

# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup node
#         uses: actions/setup-node@v1

#       - name: Bump version and push tag
#         id: bump_version
#         uses: anothrNick/github-tag-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           DEFAULT_BUMP: patch
#           DRY_RUN: true # avoid _pushing_ new tag; first, we're gonna commit manifest.json update
#           WITH_V: false

#       - name: Configure Git user
#         run: |
#           git config --global user.email "drill4j-release-bot@gmail.com"
#           git config --global user.name "drill4j-release-bot"

#       - name: Bump tag in manifest.json
#         run: ${{steps.bump_version.outputs.new_tag}}

#       - name: Build
#         run: npm install && npm run build

#       - name: Create zip archive
#         run: zip -r release.zip ./build

#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: Release ${{ github.ref }}
#           draft: false
#           prerelease: false

#       - name: Upload Release Asset
#         id: upload-release-asset 
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./release.zip
#           asset_name: release.zip
#           asset_content_type: application/zip